# This is a basic workflow to help you get started with Actions

name: Update nameserver policy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - master

  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update_nameserver_policy"
  update_nameserver_policy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ">=0.5.4"

      - name: Update nameserver policy
        working-directory: ./Clash
        run: |
          uv run update_nameserver_policy.py --config StashConfig.yaml
          uv run update_nameserver_policy.py --config MetaConfig.yaml

      - name: Should push
        run: |
          should_push=0
          [ -z "$(git diff)" ] || should_push=1
          echo "SHOULD_PUSH=$should_push" >>"$GITHUB_ENV"

      - name: Commit files
        if: env.SHOULD_PUSH == '1'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -a -m "Update rules"

      - name: Push changes
        if: env.SHOULD_PUSH == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
